export const users = [
  "Juan",
  "",
  "",
  "",
  "Oswaldo",
  "",
  "Bradley",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "Gorgonio",
  "Tim",
  "",
  "",
  "",
  "",
  "",
  "",
  "Tang",
  "Matthew",
  "",
  "",
  "Alison",
  "",
  "David",
];

export const passwords = [
  { id: 1, pw: "$2a$10$r/PfMc9ctBFLAKjKgWSIkuFdCLbQ.RdjNIDJcZV.UIeucrAU7zNsG" },
  { id: 5, pw: "$2a$10$5WkKCjM.hFR6PsgR.uGbwOjpF0bpgaIt3P/nY7QExCT6mDShYegTa" },
  { id: 7, pw: "$2a$10$HPEH1VINMgI3UMiED/uhMeD9bekz0448tyHscq5y2/b6p30yzQDQW" },
  {
    id: 23,
    pw: "$2a$10$VcClNPKjWaJy4kLDOugeAOjpnnGOwJXu5nWMZm27V7nZsgSStJ3mq",
  },
  {
    id: 24,
    pw: "$2a$10$DzbeMnVjJLrft5/2EHK8fuu1pAZhVvOV/0f4TMZDWJNRJK0/mt30y",
  },
  {
    id: 31,
    pw: "$2a$10$.8wrjwqux9PgfgX3Xm5YI.DTSC0JmTfTDpIy.Vo2ovxTqoBw9FRq.",
  },
  {
    id: 32,
    pw: "$2a$10$cTFxKn6pDqrUN.jKxdlULOX77tQ19HMmA.G57f26PI1C9/lnoRmvK",
  },
  {
    id: 35,
    pw: "$2a$10$COTSMjpjKtkjifQyjRD9F.lLRWVPMYJF3.YuyWM4E5XxQiTP9xi36",
  },
  {
    id: 37,
    pw: "$2a$10$Fwcs4yAE0JaCE7IXSQ7Yge0zXx3MhYhh8NOr14QVUNNk3bf3cmVpG",
  },
];
